config/routes.rb
Rails.application.routes.draw do
  root "main#top"

  # 新規登録
  get "signup", to: "users#new"

  # メールアドレス登録済みチェック
  post "signup/check_email", to: "users#is_registered?"

  # マイページ
  get "mypage", to: "users#show"
  get "mypage/account_setting", to: "users#edit"
  delete "account_delete", to: "users#destroy"

  # ログイン、ログアウト
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  # ゲストログイン
  post "guest_login", to: "guest_sessions#create"

  # ユーザー
  resources :users, only: [:index, :create, :update] do
    resources :address_books
    resources :add_addresses, only: [:new]
  end

  # アカウント有効化、パスワード再設定
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  # 登山計画書
  resources :plans do
    # 計画書（PDF）出力
    scope module: :pdfs do
      resources :climbing_plan, only: [:index]
    end
    resources :companions
    resources :plan_schedules
    resources :schedule_spots
    resources :plan_clubs
    resources :plan_equipments
    resources :plan_escapes
    resources :copy_plans, only: [:create]
  end

  # 計画書のサンプル(PDF)
  scope module: :pdfs do
    resources :sample_format, only: [:index]
  end

end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :remember_me, :activation_token, :reset_token
  before_create :set_id, :create_activation_digest
  before_save :downcase_email
  has_many :plans, dependent: :destroy
  has_many :address_books, dependent: :destroy

  # email オブジェクトが保存される時点で小文字に変換する
  before_save { self.email = email.downcase }

  # name のバリデーション
  validates :name, presence: true

  # email のバリデーション
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }

  # password のバリデーション
  has_secure_password
  validates :password, presence: true,
                      length: { minimum: 6 },
                      allow_nil: true


  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムな記憶トークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  # 有効化用のメールを送信する
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
    update_attribute(:activation_sent_at, Time.zone.now)
  end

  # アカウントを有効にする
  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # 有効化リンクの有効期限
  def activation_expired?
    activation_sent_at < 24.hours.ago
  end

  # パスワード再設定の属性を設定する
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # パスワード再設定のメールを送信する
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # パスワード性設定リンクの有効期限
  def password_reset_expired?
    reset_sent_at < 1.hour.ago
  end


private
  # メールアドレスを全て小文字にする
  def downcase_email
    self.email = email.downcase
  end

  # ランダムなユーザーIDを返す
  def set_id
    while self.id.blank? || User.find_by(id: self.id).present? do
      self.id = SecureRandom.base36
    end
  end

  # 有効化トークンとダイジェストを作成及び代入する
  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy ]
  before_action :require_user, only: [:show, :edit, :update, :destroy]
  before_action :require_same_user, only: [:show, :edit, :update, :destroy]
  before_action :require_verified_user, only: [:edit, :update, :destroy]
  # protect_from_forgery except: :is_registered?

  def index
    # @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:notice] = "アカウント有効化メールを送信しました。メールが届きましたら、記載されているリンクをクリックしてアカウントを有効化してください。"
      redirect_to root_url
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_url(@user), notice: "アカウント情報を更新しました"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
      redirect_to root_url, notice: "ユーザーアカウントを削除しました", status: :see_other
  end

  # メールアドレスがすでに登録されているかどうかチェックする
  def is_registered?
    user = User.find_by(email: params[:email]) # クリエパラメータに埋め込んだEメールアドレスからユーザーを検索（いなければnull)
    render json: user
  end

  private
    def set_user
      @user = User.find_by(id: current_user.id) if logged_in?
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def require_same_user
      if current_user != @user
        flash[:alert] = "ユーザーご本人以外のアクセスは禁止されています"
        redirect_to @user
      end
    end

    def require_verified_user
      if logged_in? && (current_user.email == "guest@example.com")
        redirect_to root_url, alert: "ゲストユーザーのアカウント編集・削除はできません"
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, class: "bg-light p-3 mb-5", data: { controller: "signup", action: "input->signup#validSubmit" }) do |f| %>

  <%#------- ユーザー名 --------%>
  <div class="mb-3">
    <%= icon("person") %> <%= f.label "ユーザー名(表示名)", class: "form-label required" %>
    <%= f.text_field :name, class: "form-control", data: { signup_target: "name", action: "input->signup#nameValidation" } %>
    <p data-signup-target="error_name"></p>
  </div>

  <%#------- Eメールアドレス --------%>
  <div class="mb-3">
    <% if user.new_record? %>
      <%= icon("envelope") %> <%= f.label "Eメールアドレス", class: "form-label required" %>
      <%= f.email_field :email, class: "form-control", data: { signup_target: "email", action: "input->signup#emailValidation" } %>
      <p data-signup-target="error_email"></p>
    <% else %>
      <%= icon("envelope") %> <%= f.label "Eメールアドレス(変更できません)", class: "form-label" %>
      <%= f.email_field :email, class: "form-control", disabled: true %>
    <% end %>
  </div>

  <%#------- パスワード & パスワード確認 --------%>
  <div data-action="input->signup#passwordValidation">
    <div class="mb-3">
      <%= icon("key-fill") %> <%= f.label "パスワード", class: "form-label required" %>
      <%= f.password_field :password, class: "form-control", data: { signup_target: "password" } %>
      <p data-signup-target="error_password"></p>
    </div>

    <div class="mb-3">
      <%= icon("key-fill") %> <%= f.label "パスワード(確認用)", class: "form-label required" %>
      <%= f.password_field :password_confirmation, class: "form-control", data: { signup_target: "password_confirmation" } %>
      <p data-signup-target="error_password_confirmation"></p>
    </div>
  </div>

  <%#------- 送信 --------%>
  <div class="mb-5">
    <%= f.submit class: "btn btn-primary", disabled: true, data: { signup_target: "submit", disable_with: "保存中..." } %>
    <%= link_to "キャンセル", root_path, class: "btn btn-secondary" %>
  </div>

<% end %>

app/views/users/edit.html.erb
<h1>アカウントの編集</h1>

<%= render "form", user: @user %>

<hr>
<div class="mb-5">
  <a class="btn btn-danger" href="#" data-bs-toggle="modal" data-bs-target="#accountDeleteModal"><%= icon_with_text("trash","アカウントを削除する") %></a>
  <%#= link_to icon_with_text("trash", "アカウントを削除する"), @user, class: "btn btn-danger", data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？"} %>
</div>

<!-- Modal -->
<div class="modal fade" id="accountDeleteModal" tabindex="-1" aria-labelledby="accountDeleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="accountDeleteModalLabel">確認</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        本当に削除しますか？
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
        <%= link_to "削除", account_delete_path, class: "btn btn-danger", data: { turbo_method: :delete } %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="mb-3">
  <h1>新規登録する</h1>
  <%= link_to "ログインはこちら>>", login_path %>
</div>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<h1>マイページ</h1>
<h5><%= icon_with_text("person-circle", "#{@user.name}") %></h5>

<% if current_user.email == "guest@example.com" %>
  <div class="text-danger p-3 bg-light fw-bold">
    <h5>【※注意】</h5>
    <p class="mx-2">ゲストユーザーアカウントはお試し用の共用アカウントです。</p>
    <p class="mx-2">個人を特定されるリスクを避けるため、リアルな個人情報の入力・保存はお控えください。（架空の情報であればOKです）</p>
  </div>
<% end %>

<!-- 計画書一覧 -->
<div class="card shadow mt-3 mb-4">
  <div class="card-header">
    <%= icon_with_text("file-earmark", "計画書一覧") %>
  </div>

  <div class="card-body mx-3">
    <%= link_to icon_with_text("plus-circle", "計画書を作成"),
                    new_plan_path,
                    class: "btn__basic__m btn__red mb-3 mt-1 d-block"
    %>
    <div class="row py-2">
      <div class="col-4 mt-auto fw-bold">
        登山計画書
      </div>
      <div class="col-8 mt-auto fw-bold d-flex justify-content-end">
        PDF出力 / 複製 / 編集
      </div>
      <hr class="mt-2">
    </div>
    <div class="row">
      <% @user.plans.each do |plan| %>
        <div class="col-5 mt-auto">
          <%= link_to plan.destination, plan %>
        </div>

        <div class="col-7 text-end">
          <%= link_to icon("file-earmark-pdf"), plan_climbing_plan_index_path(plan, format: "pdf"), class: "btn btn-outline-danger" %>
          <%= link_to icon("clipboard-check"), plan_copy_plans_path(plan), class: "btn btn-outline-success", data: { turbo_method: :post } %>
          <%= link_to "編集", edit_plan_path(plan) , class: "btn btn-outline-primary" %>
        </div>
        <hr class="mt-2" style="border: 1px solid #ccc">
      <% end %>
    </div>

    <!-- <div class="d-flex justify-content-end mt-3">
      <%#= paginate @cats %>
    </div> -->
  </div>
</div>