config/routes.rb
Rails.application.routes.draw do
  root "main#top"

  # 新規登録
  get "signup", to: "users#new"

  # メールアドレス登録済みチェック
  post "signup/check_email", to: "users#is_registered?"

  # マイページ
  get "mypage", to: "users#show"
  get "mypage/account_setting", to: "users#edit"
  delete "account_delete", to: "users#destroy"

  # ログイン、ログアウト
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  # ゲストログイン
  post "guest_login", to: "guest_sessions#create"

  # ユーザー
  resources :users, only: [:index, :create, :update] do
    resources :address_books
    resources :add_addresses, only: [:new]
  end

  # アカウント有効化、パスワード再設定
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  # 登山計画書
  resources :plans do
    # 計画書（PDF）出力
    scope module: :pdfs do
      resources :climbing_plan, only: [:index]
    end
    resources :companions
    resources :plan_schedules
    resources :schedule_spots
    resources :plan_clubs
    resources :plan_equipments
    resources :plan_escapes
    resources :copy_plans, only: [:create]
  end

  # 計画書のサンプル(PDF)
  scope module: :pdfs do
    resources :sample_format, only: [:index]
  end

end

app/models/address_book.rb
class AddressBook < ApplicationRecord
  encrypts :full_name, :gender, :address, :phone_number, :emergency_contact, :emergency_number
  belongs_to :user

  with_options presence: true do
    validates :full_name
    validates :age
    validates :address
    validates :phone_number
    validates :emergency_contact
    validates :emergency_number
  end

  private
    # @companion情報からアドレス帳の作成
    def self.create_address_book(companion, user)
      create!(full_name: companion.full_name,
              gender: companion.gender,
              birthday: companion.birthday,
              age: companion.age,
              address: companion.address,
              phone_number: companion.phone_number,
              emergency_contact: companion.emergency_contact,
              emergency_number: companion.emergency_number,
              user_id: user.id
              )
    end
end

app/controllers/address_books_controller.rb
class AddressBooksController < ApplicationController
  before_action :set_address_book, only: [ :edit, :update, :destroy]
  before_action :set_user
  before_action :require_user

  def index
    @address_books = @user.address_books
  end

  def new
    @address_book = AddressBook.new
  end

  def edit
  end

  def create
    @address_book = AddressBook.new(address_book_params)
    @address_book.user = @user
    if @address_book.save
      flash[:notice] = "アドレス情報が追加されました"
      redirect_to user_address_books_path(@user)
    else
      render "new", status: :unprocessable_entity
    end
  end

  def update
    if @address_book.update(address_book_params)
      flash[:notice] = "アドレス情報が更新されました"
      redirect_to user_address_books_path(@user)
    else
      render "edit", status: :unprocessable_entity
    end
  end

  def destroy
    @address_book.destroy
    redirect_to user_address_books_path(@user), notice: "アドレス情報が1件削除されました", status: :see_other
  end


  private
    def set_user
      @user = User.find(params[:user_id])
    end

    def set_address_book
      @address_book = AddressBook.find(params[:id])
    end

    def address_book_params
      params.require(:address_book).permit(:full_name, :gender, :birthday, :age, :address, :phone_number, :emergency_contact, :emergency_number)
    end

    def require_same_user
      if current_user != @address_book.user
        flash[:alert] = "ユーザーご本人以外のアクセスは禁止されています"
        redirect_to current_user
      end
    end
end

app/helpers/address_books_helper.rb
module AddressBooksHelper
end

app/views/address_books/_form.html.erb
<%= form_with(model: [@user, @address_book], local: true, class: "mb-5 bg-light p-3") do |f| %>

  <div class="mb-3 <%= @address_book.errors.include?(:full_name) ? "validation_errors" : "" %>">
    <%= icon("person") %> <%= f.label "氏名", for: "addressFullName", class: "form-label" %>
    <%= f.text_field :full_name, placeholder: "例）山田 太郎", class: "form-control", id: "addressFullName"%>
    <%= render 'layouts/error',class: "invalid-feedback", obj: @address_book, key: :full_name %>
  </div>

  <div class="mb-3">
    <%= icon("calendar-date") %> <%= f.label "生年月日", class: "form-label" %>
    <div class="">
      <%= f.date_select :birthday,
        {use_month_numbers: true,
        start_year: 1950,
        end_year: (Time.now.year - 10),
        default: Date.new(1990, 1, 1),
        date_separator: '/ '},
        {class: "form__custom"} %>
    </div>
  </div>

  <div class="mb-3 <%= @address_book.errors.include?(:age) ? "validation_errors" : "" %>">
    <%= icon("person") %> <%= f.label "年齢", for: "addressAge", class: "form-label" %>
    <%= f.number_field :age, class: "form-control", id: "addressAge", placeholder: "半角数字で入力してください 例）20"%>
    <%= render 'layouts/error',class: "invalid-feedback", obj: @address_book, key: :age %>
  </div>

  <div class="mb-3">
    <%= icon("gender-ambiguous") %> <%= f.label "性別", class: "form-label" %>
      <br>
      <%= f.radio_button :gender, "男" , class: "form-check-input mx-1", id: "addressGenderMale", checked: true %>
      <%= f.label "男性", for: "addressGenderMale" %>
      <span class="mx-1"></span>
      <%= f.radio_button :gender, "女" , class: "form-check-input mx-1", id: "addressGenderFemale"%>
      <%= f.label "女性", for: "addressGenderFemale" %>

  </div>

  <div class="mb-3 <%= @address_book.errors.include?(:address) ? "validation_errors" : "" %>">
    <%= icon("mailbox2") %> <%= f.label "住所", for: "addressAddress", class: "form-label" %>
    <%= f.text_field :address, placeholder: "例）東京都墨田区押上１丁目１−２", class: "form-control", id: "addressAddress"%>
    <%= render 'layouts/error',class: "invalid-feedback", obj: @address_book, key: :address %>
  </div>

  <div class="mb-3 <%= @address_book.errors.include?(:phone_number) ? "validation_errors" : "" %>">
    <%= icon("telephone-plus") %> <%= f.label "電話番号（自宅or携帯）", for: "addressPhoneNumber", class: "form-label" %>
    <%= f.text_field :phone_number, placeholder: "例）090-1234-5678", class: "form-control", id: "addressPhoneNumber"%>
    <%= render 'layouts/error',class: "invalid-feedback", obj: @address_book, key: :phone_number %>
  </div>

  <div class="mb-3 <%= @address_book.errors.include?(:emergency_contact) ? "validation_errors" : "" %>">
    <%= icon("person") %> <%= f.label "緊急連絡先（間柄）", for: "addressEmergencyContact", class: "form-label" %>
    <%= f.text_field :emergency_contact, placeholder: "例）山田 花子（母）", class: "form-control", id: "addressEmergencyContact"%>
    <%= render 'layouts/error',class: "invalid-feedback", obj: @address_book, key: :emergency_contact %>
  </div>

  <div class="mb-3 <%= @address_book.errors.include?(:emergency_number) ? "validation_errors" : "" %>">
    <%= icon("telephone-plus") %> <%= f.label "緊急連絡先の電話番号（自宅or携帯）", for: "addressEmergencyNumber", class: "form-label" %>
    <%= f.text_field :emergency_number, placeholder: "例）052-123-4567", class: "form-control", id: "addressEmergencyNumber"%>
    <%= render 'layouts/error',class: "invalid-feedback", obj: @address_book, key: :emergency_number %>
  </div>

  <%= f.submit "登録する", class: "btn btn-primary" %>
  <%= link_to "キャンセル", user_address_books_path(current_user) , class: "btn btn-secondary"%>
<% end %>

app/views/address_books/edit.html.erb
<h1>アドレス情報の編集</h1>

<%= render "form" %>

app/views/address_books/index.html.erb
<h1><%= current_user.name %>さんのアドレス帳</h1>

<!-- アドレス帳一覧 -->
<div class="card shadow mt-3 mb-5">
  <div class="card-header">
    <%= icon_with_text("book", "アドレス帳一覧") %>
  </div>

  <div class="card-body mx-3">
    <%= link_to icon_with_text("plus-circle", "追加"),
                    new_user_address_book_path(@user),
                    class: "btn__basic__m btn__red mb-3 mt-1 d-block"
    %>
    <div class="row py-2">
      <div class="col-4 mt-auto fw-bold">
        氏名
      </div>
      <div class="col-3 mt-auto fw-bold">
        性別
      </div>
      <div class="col-5 mt-auto fw-bold d-flex justify-content-end">
        編集/削除
      </div>
      <hr class="mt-2">
    </div>
    <div class="row">
      <% @address_books.each do |address| %>
        <div class="col-4 mt-auto">
          <%= address.full_name %>
        </div>
        <div class="col-3 mt-auto">
          <%= address.gender %>
        </div>

        <div class="col-5 text-end">
          <%#= link_to icon("file-earmark-pdf"), plan_climbing_plan_index_path(plan, format: "pdf"), class: "btn btn-outline-danger" %>
          <%#= link_to icon("clipboard-check"), plan, class: "btn btn-outline-success" %>
          <%= link_to "編集", edit_user_address_book_path(address.user_id, address.id) , class: "btn btn-outline-primary" %>
          <%= link_to icon("trash"), user_address_book_path(address.user_id, address.id), class: "btn btn-outline-danger", data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？"} %>
        </div>
        <hr class="mt-2" style="border: 1px solid #ccc">
      <% end %>
    </div>

    <!-- <div class="d-flex justify-content-end mt-3">
      <%#= paginate @cats %>
    </div> -->
  </div>
</div>

app/views/address_books/new.html.erb
<h1>アドレス情報の追加</h1>

<%= render "form" %>