config/routes.rb
Rails.application.routes.draw do
  root "main#top"

  # 新規登録
  get "signup", to: "users#new"

  # メールアドレス登録済みチェック
  post "signup/check_email", to: "users#is_registered?"

  # マイページ
  get "mypage", to: "users#show"
  get "mypage/account_setting", to: "users#edit"
  delete "account_delete", to: "users#destroy"

  # ログイン、ログアウト
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  # ゲストログイン
  post "guest_login", to: "guest_sessions#create"

  # ユーザー
  resources :users, only: [:index, :create, :update] do
    resources :address_books
    resources :add_addresses, only: [:new]
  end

  # アカウント有効化、パスワード再設定
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  # 登山計画書
  resources :plans do
    # 計画書（PDF）出力
    scope module: :pdfs do
      resources :climbing_plan, only: [:index]
    end
    resources :companions
    resources :plan_schedules
    resources :schedule_spots
    resources :plan_clubs
    resources :plan_equipments
    resources :plan_escapes
    resources :copy_plans, only: [:create]
  end

  # 計画書のサンプル(PDF)
  scope module: :pdfs do
    resources :sample_format, only: [:index]
  end

end

app/models/plan.rb
class Plan < ApplicationRecord
  before_create :set_plan_id
  has_many :companions, dependent: :destroy
  has_many :plan_schedules, dependent: :destroy
  has_one :plan_club, dependent: :destroy
  has_one :plan_equipment, dependent: :destroy
  has_one :plan_escape, dependent: :destroy
  belongs_to :user

  validates :destination, presence: true, length: { maximum: 30 }
  validates :start_day, presence: true
  validates :last_day, presence: true

  private
  def set_plan_id
    while self.id.blank? || Plan.find_by(id: self.id).present? do
      self.id = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: %i[ show edit update destroy ]
  before_action :require_user
  before_action :require_same_user, only: %i[ show edit update destroy ]

  def index
    @plans = Plan.where(id: current_user.id)
  end

  def show
  end

  def new
    @plan = Plan.new
  end

  def edit
  end

  def create
    @plan = Plan.new(plan_params)
    @plan.user = current_user
    if @plan.save
      redirect_to @plan, notice: '新規計画書を追加しました。引き続き、計画書の作成を進めてください。'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @plan.update(plan_params)
      redirect_to @plan , notice: '登山計画書が更新されました'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @plan.destroy
    redirect_to mypage_path, notice: '計画書が削除されました', status: :see_other
  end

  private
    def set_plan
      @plan = Plan.find(params[:id])
    end

    def plan_params
      params.require(:plan).permit(:destination, :submit_to, :start_day, :last_day)
    end

    def require_same_user
      if current_user != @plan.user
        flash[:alert] = "異なるユーザーからのアクセスは禁止されています"
        redirect_to root_path
      end
    end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<%= bootstrap_form_with(model: plan, class: "mb-5 bg-light p-3") do |f| %>
  <%= f.text_field :destination, placeholder: "例）北アルプス 白馬岳" %>
  <%= f.date_field :start_day %>
  <%= f.date_field :last_day %>
  <%= f.text_field :submit_to, placeholder: "例）長野県警察本部" %>
  <%= f.primary %>
  <%= link_to "キャンセル", mypage_path , class: "btn btn-secondary"%>
<% end %>

app/views/plans/edit.html.erb
<h1>計画書を編集</h1>

<%= render "form", plan: @plan %>

<hr>
<div class="mb-5">
  <%= link_to icon_with_text("trash", "計画書を削除する"), @plan, class: "btn btn-danger", data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？"} %>
</div>

app/views/plans/index.html.erb
<!-- 計画書一覧 -->
<div class="card shadow mt-3 mb-5">
  <div class="card-header">
    <%= icon_with_text("file-earmark", "計画書一覧") %>
  </div>

  <div class="card-body mx-3">
    <%= link_to icon_with_text("plus-circle", "計画書を作成"),
                    new_plan_path,
                    class: "btn__basic__m btn__red mb-3 mt-1 d-block"
    %>
    <div class="row py-2">
      <div class="col-4 mt-auto fw-bold">
        登山計画書
      </div>
      <div class="col-8 mt-auto fw-bold d-flex justify-content-end">
        PDF出力 / 複製 / 編集
      </div>
      <hr class="mt-2">
    </div>
    <div class="row">
      <% current_user.plans.each do |plan| %>
        <div class="col-5 mt-auto">
          <%= link_to plan.destination, plan %>
        </div>

        <div class="col-7 text-end">
          <%= link_to icon("file-earmark-pdf"), plan_climbing_plan_index_path(plan, format: "pdf"), class: "btn btn-outline-danger" %>
          <%= link_to icon("clipboard-check"), plan, class: "btn btn-outline-success" %>
          <%= link_to "編集", edit_plan_path(plan) , class: "btn btn-outline-primary" %>
        </div>
        <hr class="mt-2" style="border: 1px solid #ccc">
      <% end %>
    </div>

    <!-- <div class="d-flex justify-content-end mt-3">
      <%#= paginate @cats %>
    </div> -->
  </div>
</div>

app/views/plans/new.html.erb
<h1>計画書を作成</h1>

<%= render "form", plan: @plan %>

app/views/plans/show.html.erb
<div class="mb-3">
  <%= link_to icon_with_text("box-arrow-in-left", "計画書一覧に戻る"), mypage_path %>
</div>
<h1 class="mb-5"><%= @plan.destination %></h1>
<h4>◉山行期間</h4>
<div class="mb-5">
<% if @plan.start_day.to_s == @plan.last_day.to_s %>
  <%= l @plan.start_day, format: :long %>
<% else %>
  <%= l @plan.start_day, format: :long %> ~ <%= l @plan.last_day, format: :short_ja %>
<% end %>
</div>

<h4>◉登山者名簿の登録</h4>
<span class="text-danger" style="font-size: 0.8em">※最大６人まで登録できます</span>
<%#------- 登山者名簿 -------%>
<div class="card shadow-sm mt-3 mb-5">
  <div class="card-body mx-3">
    <div class="row py-2">
      <div class="col-4 mt-auto fw-bold">
        氏名
      </div>
      <div class="col-3 mt-auto fw-bold">
        役割
      </div>
      <div class="col-5 mt-auto fw-bold d-flex justify-content-end">

      </div>
      <hr class="mt-2">
    </div>
    <div class="row">
      <% @plan.companions.order(role: "ASC").each do |companion| %>
        <div class="col-4 mt-auto">
          <%= companion.full_name %>
          <%#= link_to companion.full_name, plan_companion_path(companion.plan_id, companion.id) %>
        </div>
        <div class="col-3 mt-auto">
          <%=  companion.role != "X" ? companion.role : icon("dash-lg")  %>
          <%#= companion.gender %>
        </div>
        <div class="col-5 text-end">
          <%= link_to "編集", edit_plan_companion_path(companion.plan_id, companion.id) , class: "btn btn-outline-primary" %>
          <%= link_to icon("trash"), plan_companion_path(companion.plan_id, companion.id), class: "btn btn-outline-danger", data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？"}%>
        </div>
        <hr class="mt-2" style="border: 1px solid #ccc">
      <% end %>
    </div>
    <% if @plan.companions.length < 6 %>
      <%= link_to icon_with_text("plus-circle", "追加"),
                      new_plan_companion_path(@plan),
                      class: "btn__basic__m btn__green mb-3 mt-1 d-block"
      %>
    <% end %>
  </div>
</div>

<h4>◉行動スケジュールの登録</h4>
<span class="text-danger" style="font-size: 0.8em">※最大５件まで登録できます</span>
<%#------- 登山者名簿 -------%>
<div class="card shadow-sm mt-3 mb-5">
  <div class="card-body mx-3">
    <div class="row py-2">
      <div class="col-3 mt-auto fw-bold">
        日付
      </div>
      <div class="col-4 mt-auto fw-bold">
        行動予定
      </div>
      <div class="col-5 mt-auto fw-bold d-flex justify-content-end">

      </div>
      <hr class="mt-2">
    </div>
    <div class="row">
      <% @plan.plan_schedules.order(date: "ASC").each do |schedule| %>
        <div class="col-3 mt-auto">
          <% if !schedule.date.nil? %>
            <%= l schedule.date, format: :short %>
          <% end %>
          <%#= link_to companion.full_name, plan_companion_path(companion.plan_id, companion.id) %>
        </div>
        <div class="col-4 mt-auto">
          <%#= truncate(schedule.schedule_spots, length: 12) %>
          <% schedule.schedule_spots.each_with_index do |spot, index| %>
            <% if index < 2 %>
              <%= "--" if !(index == 0) %> <%= spot["spot"] %> <%= "..." if (index == 1) %>
            <% end %>
          <% end %>
          <%#= companion.gender %>
        </div>
        <div class="col-5 text-end">
          <%= link_to "編集", edit_plan_plan_schedule_path(schedule.plan_id, schedule.id) , class: "btn btn-outline-primary" %>
          <%= link_to icon("trash"), plan_plan_schedule_path(schedule.plan_id, schedule.id), class: "btn btn-outline-danger", data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？"}%>
        </div>
        <hr class="mt-2" style="border: 1px solid #ccc">
      <% end %>
    </div>
    <% if @plan.plan_schedules.length < 5 %>
      <%= link_to icon_with_text("plus-circle", "追加"),
                      new_plan_plan_schedule_path(@plan),
                      class: "btn__basic__m btn__green mb-3 mt-1 d-block"
      %>
    <% end %>
  </div>
</div>

<h4>◉エスケープルートの登録</h4>
<div class="mb-5">
  <% if @plan.plan_escape.nil? %>
    <%= link_to icon_with_text("plus-circle", "追加"),
                      new_plan_plan_escape_path(@plan),
                      class: "btn__basic__m btn__green mb-3 mt-1 d-block"
      %>
  <% else %>
    <%= link_to icon_with_text("pencil-square", "編集"),
                      edit_plan_plan_escape_path(@plan.id, @plan.plan_escape.id),
                      class: "btn__basic__m mb-3 mt-1 d-block"
      %>
  <% end %>
</div>

<h4>◉持ち物情報の登録</h4>
<div class="mb-5">
  <% if @plan.plan_equipment.nil? %>
    <%= link_to icon_with_text("plus-circle", "追加"),
                      new_plan_plan_equipment_path(@plan),
                      class: "btn__basic__m btn__green mb-3 mt-1 d-block"
      %>
  <% else %>
    <%= link_to icon_with_text("pencil-square", "編集"),
                      edit_plan_plan_equipment_path(@plan.id, @plan.plan_equipment.id),
                      class: "btn__basic__m mb-3 mt-1 d-block"
      %>
  <% end %>
</div>

<h4>◉所属している山岳会など（あれば）</h4>
<span class="text-danger" style="font-size: 0.8em">※未登録の場合はPDFの山岳会の項目に「無所属」と表記されます</span>
<div class="mb-5">
  <% if @plan.plan_club.nil? %>
    <%= link_to icon_with_text("plus-circle", "追加"),
                      new_plan_plan_club_path(@plan),
                      class: "btn__basic__m btn__green mb-3 mt-1 d-block"
      %>
  <% else %>
    <%= link_to icon_with_text("pencil-square", "編集"),
                      edit_plan_plan_club_path(@plan.id, @plan.plan_club.id),
                      class: "btn__basic__m mb-3 mt-1 d-block"
      %>
  <% end %>
</div>

<%#------- PDF出力ボタン -------%>
<h4>◉PDFの出力</h4>
<span class="text-danger" style="font-size: 0.8em">※入力した情報がPDFに反映されます↓</span>
<div class="mt-2 mb-4">
  <%= link_to icon_with_text("file-earmark-pdf", "PDFを出力する"), plan_climbing_plan_index_path(@plan, format: "pdf"), class: "btn__basic__l", style: "background: #B30B01" %>
</div>

<div class="mb-5">
  <%= link_to icon_with_text("box-arrow-in-left", "計画書一覧に戻る"), mypage_path %>
</div>