config/routes.rb
Rails.application.routes.draw do
  root "main#top"

  # 新規登録
  get "signup", to: "users#new"

  # メールアドレス登録済みチェック
  post "signup/check_email", to: "users#is_registered?"

  # マイページ
  get "mypage", to: "users#show"
  get "mypage/account_setting", to: "users#edit"
  delete "account_delete", to: "users#destroy"

  # ログイン、ログアウト
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  # ゲストログイン
  post "guest_login", to: "guest_sessions#create"

  # ユーザー
  resources :users, only: [:index, :create, :update] do
    resources :address_books
    resources :add_addresses, only: [:new]
  end

  # アカウント有効化、パスワード再設定
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  # 登山計画書
  resources :plans do
    # 計画書（PDF）出力
    scope module: :pdfs do
      resources :climbing_plan, only: [:index]
    end
    resources :companions
    resources :plan_schedules
    resources :schedule_spots
    resources :plan_clubs
    resources :plan_equipments
    resources :plan_escapes
    resources :copy_plans, only: [:create]
  end

  # 計画書のサンプル(PDF)
  scope module: :pdfs do
    resources :sample_format, only: [:index]
  end

end

app/models/address_book.rb
class AddressBook < ApplicationRecord
  encrypts :full_name, :gender, :address, :phone_number, :emergency_contact, :emergency_number
  belongs_to :user

  with_options presence: true do
    validates :full_name
    validates :age
    validates :address
    validates :phone_number
    validates :emergency_contact
    validates :emergency_number
  end

  private
    # @companion情報からアドレス帳の作成
    def self.create_address_book(companion, user)
      create!(full_name: companion.full_name,
              gender: companion.gender,
              birthday: companion.birthday,
              age: companion.age,
              address: companion.address,
              phone_number: companion.phone_number,
              emergency_contact: companion.emergency_contact,
              emergency_number: companion.emergency_number,
              user_id: user.id
              )
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/companion.rb
class Companion < ApplicationRecord
  attr_accessor :add_address, :selected_id
  encrypts :full_name, :gender, :address, :phone_number, :emergency_contact, :emergency_number
  belongs_to :plan

  with_options presence: true do
    validates :full_name
    validates :age
    validates :address
    validates :phone_number
    validates :emergency_contact
    validates :emergency_number
  end
end

app/models/plan.rb
class Plan < ApplicationRecord
  before_create :set_plan_id
  has_many :companions, dependent: :destroy
  has_many :plan_schedules, dependent: :destroy
  has_one :plan_club, dependent: :destroy
  has_one :plan_equipment, dependent: :destroy
  has_one :plan_escape, dependent: :destroy
  belongs_to :user

  validates :destination, presence: true, length: { maximum: 30 }
  validates :start_day, presence: true
  validates :last_day, presence: true

  private
  def set_plan_id
    while self.id.blank? || Plan.find_by(id: self.id).present? do
      self.id = SecureRandom.urlsafe_base64
    end
  end
end

app/models/plan_club.rb
class PlanClub < ApplicationRecord
  belongs_to :plan
  encrypts :representative_name, :representative_address, :representative_number, :address, :phone_number, :emergency_contact

  with_options presence: true do
    validates :belongs_to
    validates :representative_name
    validates :representative_address
    validates :representative_number
    validates :address
    validates :phone_number
    validates :emergency_contact
    validates :rescue_system
  end
end

app/models/plan_equipment.rb
class PlanEquipment < ApplicationRecord
  belongs_to :plan

  with_options presence: true do
    validates :food
    validates :emergency_food
  end
end

app/models/plan_escape.rb
class PlanEscape < ApplicationRecord
  belongs_to :plan

  validates :escape_route, presence: true
end

app/models/plan_schedule.rb
class PlanSchedule < ApplicationRecord
  has_many :schedule_spots, dependent: :destroy
  belongs_to :plan

  # accepts_nested_attributes_for :schedule_spots, allow_destroy: true

  validates :date, presence: true

end

app/models/schedule_spot.rb
class ScheduleSpot < ApplicationRecord
  belongs_to :plan_schedule

  # with_options presence: true do
  #   validates :spot
  #   validates :time
  # end

end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :remember_me, :activation_token, :reset_token
  before_create :set_id, :create_activation_digest
  before_save :downcase_email
  has_many :plans, dependent: :destroy
  has_many :address_books, dependent: :destroy

  # email オブジェクトが保存される時点で小文字に変換する
  before_save { self.email = email.downcase }

  # name のバリデーション
  validates :name, presence: true

  # email のバリデーション
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }

  # password のバリデーション
  has_secure_password
  validates :password, presence: true,
                      length: { minimum: 6 },
                      allow_nil: true


  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムな記憶トークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  # 有効化用のメールを送信する
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
    update_attribute(:activation_sent_at, Time.zone.now)
  end

  # アカウントを有効にする
  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # 有効化リンクの有効期限
  def activation_expired?
    activation_sent_at < 24.hours.ago
  end

  # パスワード再設定の属性を設定する
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # パスワード再設定のメールを送信する
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # パスワード性設定リンクの有効期限
  def password_reset_expired?
    reset_sent_at < 1.hour.ago
  end


private
  # メールアドレスを全て小文字にする
  def downcase_email
    self.email = email.downcase
  end

  # ランダムなユーザーIDを返す
  def set_id
    while self.id.blank? || User.find_by(id: self.id).present? do
      self.id = SecureRandom.base36
    end
  end

  # 有効化トークンとダイジェストを作成及び代入する
  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def top
    redirect_to mypage_path if logged_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # bootstrapのアイコンを生成するメソッド
  def icon(icon_name)
    tag.i(class: ["bi", "bi-#{icon_name}"])
  end

  # bootstrapの「アイコン＋文字列」を生成するメソッド
  def icon_with_text(icon_name, text)
    tag.span(icon(icon_name), class: "me-2") + tag.span(text)
  end

end

app/helpers/companions_helper.rb
module CompanionsHelper
end

app/helpers/copy_plans_helper.rb
module CopyPlansHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/plan_clubs_helper.rb
module PlanClubsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error.html.erb
<% if obj.errors.include?(key) %>
    <% obj.errors.full_messages_for(key).each do |error| %>
      <li style="list-style:none; font-size: 0.8em" class="text-danger validation_font_size">※必須項目です</li>
      <!-- <li style="list-style:none; font-size: 0.8em" class="text-danger validation_font_size"> <%= error %>必須項目です</li> -->
    <% end %>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; <%= link_to "Hiroki Kobayashi", "https://kobacchi.com", class: "text-white" %></small>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<!-- ナビゲーションメニュー -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <%= link_to icon_with_text("phone", "スマホ de 登山計画書"), (logged_in? ? mypage_path : root_path), class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= icon_with_text("file-earmark","計画書メニュー") %>

            </a>
            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
              <li><%= link_to icon_with_text("file-earmark", "新規計画書作成"), new_plan_path, class: "dropdown-item" %></li>
              <li><%= link_to icon_with_text("download", "計画書サンプル(PDF)"), sample_format_index_path(format: "pdf"), class: "dropdown-item" %></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= icon_with_text("person-circle","アカウントメニュー") %>

            </a>
            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
              <li><%= link_to icon_with_text("person-circle","マイページ"), mypage_path, class: "dropdown-item" %></li>
              <li><%= link_to icon_with_text("book","アドレス帳"), user_address_books_path(current_user), class: "dropdown-item"%></li>
              <% if current_user.email != "guest@example.com" %>
                <li><%= link_to icon_with_text("gear","アカウント設定"), mypage_account_setting_path, class: "dropdown-item"%></li>
              <% end %>
              <li>
                <a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#exampleModal"><%= icon_with_text("box-arrow-right","ログアウト") %></a>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to icon_with_text("person-plus", "新規登録"), signup_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to icon_with_text("box-arrow-in-right", "ログイン"), login_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">確認</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <% if logged_in?%>
        <div class="modal-body">
          本当にログアウトしますか？
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
          <%= button_to "ログアウト", logout_path, class: "btn btn-danger", method: :delete %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>登山計画書メーカー</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- <meta name="turbo-cache-control" content="no-cache"> -->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="footer__fixed">
      <%= render 'layouts/navigation' %>
      <div id="page-content">
        <div class="container mt-4">
          <div id="flash">
            <%= render 'layouts/flash' %>
          </div>
          <%= yield %>
          <% if Rails.env.development? %>
            <div class="text-bg-light py-2 px-3 shadow-sm rounded">
              <p><%= debug(params) %></p>
              <p>セッションID => <%= session[:user_id] %></p>
            </div>
          <% end %>
        </div>
      </div>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>